## Cluster configs

apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: ${CLUSTER_NAME}
  controlPlaneRef:
    kind: TalosControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: ${CLUSTER_NAME}-controlplane
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  region: ${AWS_REGION}
  sshKeyName: ${AWS_SSH_KEY_NAME}
  network:
    vpc:
      id: ${AWS_VPC_ID}
    subnets:
      - id: ${AWS_SUBNET}
---
## Control plane configs

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-controlplane
spec:
  template:
    spec:
      cloudInit:
        insecureSkipSecretsManager: true
      instanceType: ${AWS_CONTROL_PLANE_MACHINE_TYPE}
      rootVolume:
        size: ${AWS_CONTROL_PLANE_VOL_SIZE}
      sshKeyName: ${AWS_SSH_KEY_NAME}
      ami:
        id: ${AWS_CONTROL_PLANE_AMI_ID}
      additionalSecurityGroups: ${AWS_CONTROL_PLANE_ADDL_SEC_GROUPS}
      publicIP: true
      iamInstanceProfile: ${AWS_CONTROL_PLANE_IAM_PROFILE}
      subnet:
        id: ${AWS_SUBNET}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: ${CLUSTER_NAME}-controlplane
spec:
  version: v${KUBERNETES_VERSION}
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  infrastructureTemplate:
    kind: AWSMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: ${CLUSTER_NAME}-controlplane
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: ${TALOS_VERSION}
      configPatches:
        - op: add
          path: /cluster/network/cni
          value:
            name: custom
            urls:
              - https://docs.projectcalico.org/${CALICO_VERSION}/manifests/calico.yaml
        - op: add
          path: /machine/kubelet/registerWithFQDN
          value: true
        - op: add
          path: /cluster/externalCloudProvider
          value:
            enabled: true
            manifests:
              - https://raw.githubusercontent.com/kubernetes/cloud-provider-aws/${CLOUD_PROVIDER_VERSION}/manifests/rbac.yaml
              - https://raw.githubusercontent.com/kubernetes/cloud-provider-aws/${CLOUD_PROVIDER_VERSION}/manifests/aws-cloud-controller-manager-daemonset.yaml
---
## Worker machinepool configs

apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfig
metadata:
  name: ${CLUSTER_NAME}-workers
spec:
  generateType: join
  talosVersion: ${TALOS_VERSION}
  configPatches:
    - op: add
      path: /machine/kubelet/registerWithFQDN
      value: true
    - op: add
      path: /cluster/externalCloudProvider
      value:
        enabled: true
---
apiVersion: exp.cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: ${CLUSTER_NAME}-workers
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${AWS_WORKER_POOL_DESIRED}
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfig
          name: ${CLUSTER_NAME}-workers
      clusterName: ${CLUSTER_NAME}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachinePool
        name: ${CLUSTER_NAME}-workers
      version: ${KUBERNETES_VERSION}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachinePool
metadata:
  name: ${CLUSTER_NAME}-workers
spec:
  minSize: ${AWS_WORKER_POOL_MIN}
  maxSize: ${AWS_WORKER_POOL_MAX}
  awsLaunchTemplate:
    instanceType: ${AWS_NODE_MACHINE_TYPE}
    sshKeyName: ${AWS_SSH_KEY_NAME}
    additionalSecurityGroups: ${AWS_NODE_ADDL_SEC_GROUPS}
    rootVolume:
      size: ${AWS_NODE_VOL_SIZE}
    ami:
      id: ${AWS_NODE_AMI_ID}
    iamInstanceProfile: ${AWS_NODE_IAM_PROFILE}
---
